### ISSUE TITLE
Custom UTF8 stream decoding overhead/gain

### ISSUE THREAD

**Issue by dweiss** [mmastrac/nanojson#48]
Just FYI. The custom handling of UTF8 in JsonTokener is impressive but made me wonder how much is actually there to gain (compared to a buffered reader over a decoding stream). I made a quick wall-time repeated check parsing a contiguous json (with majority in plain ascii but containing some more complex multibyte sequences). The input file is ~350MB and fits entirely in I/O caches.

After a small JVM warmup of a few rounds, the results stabilized around:

internal utf8-decoder: ~1.57 seconds
JDK's utf8-decoder (reader): ~2.00 seconds

So the gain is there but really tiny considering that you typically also do something to the result (and this dominates raw parsing).

**Comment by mmastrac** [comment]
Thanks for re-confirming this! I originally used the system UTF-8 decoder and one of the places we lost out to GSON/Jackson/etc was because they had their own custom decode path. 

TBH I'm surprised it's still a gain but this is something to keep an eye on. It was the source of a _very_ obscure, _very_ rare bug that survived in hiding for 5 years (!), so getting rid of it when it's no longer a benefit is probably worth it.

**Comment by dweiss** [comment]
I imagine. I actually removed it from a local fork of nanojson that I have just because I wasn't using it - keeping a  custom UTF8 decoder is a pain and, unless you're dealing with gigantic traffic, probably not worth the effort.
